language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
# install dependencies
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo pip install python-dateutil
  # intall the 'guess language' module
  - sudo pip install pyenchant
  - sudo apt-get install hunspell-en-us hunspell-ru hunspell-de-de hunspell-fr hunspell-eu-es
  - sudo pip install --pre guess_language-spirit
install: 
  # - python setup.py dev
# run tests
script: nosetests
